/**
 * Bundles the Vortex-side parity runner.
 *
 * The runner imports Vortex's real algorithm files out of a Vortex checkout.
 * Only one leaf module is substituted: `@/extensions/nexus_integration/util/UIDs`,
 * whose single runtime export the mapper uses is the VORTEX_MOD_UID constant.
 * Pulling in the real module would drag in Vortex's whole renderer graph, so a
 * stub supplies the constant — and this script asserts the stub's literal still
 * matches the real source, so the substitution can never silently drift.
 *
 * Usage: node build.mjs [--vortex <path to Vortex checkout>]
 */

import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

const argIndex = process.argv.indexOf("--vortex");
const vortexRoot = resolve(
  argIndex !== -1 && process.argv[argIndex + 1]
    ? process.argv[argIndex + 1]
    : join(here, "..", "..", "..", "..", "vortex"),
);

const resolverEntry = join(
  vortexRoot,
  "packages/file-dependency-resolver/src/index.ts",
);
const mapperEntry = join(
  vortexRoot,
  "src/renderer/src/extensions/health_check/utils/fileRequirements/mapRequirementsReport.ts",
);
const contentEntry = join(
  vortexRoot,
  "src/renderer/src/extensions/health_check/views/content/FileRequirementsContent.tsx",
);
const realUIDsPath = join(
  vortexRoot,
  "src/renderer/src/extensions/nexus_integration/util/UIDs.ts",
);
const realCheckPath = join(
  vortexRoot,
  "src/renderer/src/extensions/health_check/checks/fileRequirementsCheck.ts",
);

for (const [label, path] of [
  ["resolver", resolverEntry],
  ["mapper", mapperEntry],
  ["UIDs", realUIDsPath],
  ["listing content", contentEntry],
  ["file requirements check", realCheckPath],
]) {
  try {
    readFileSync(path, "utf8");
  } catch {
    console.error(`Cannot find Vortex ${label} source at:\n  ${path}`);
    console.error(`Pass --vortex <path-to-Vortex-checkout> if it lives elsewhere.`);
    process.exit(2);
  }
}

// --- pin the one substituted constant against the real source ---------------

const realUIDs = readFileSync(realUIDsPath, "utf8");
const match = realUIDs.match(/export const VORTEX_MOD_UID\s*=\s*"([0-9]+)"/);
if (!match) {
  console.error(
    `Could not read VORTEX_MOD_UID out of ${realUIDsPath}.\n` +
      `The mapper's suppression rule depends on it; refusing to build a stub ` +
      `that might disagree with Vortex.`,
  );
  process.exit(2);
}
const vortexModUid = match[1];
console.log(`VORTEX_MOD_UID pinned from Vortex source: ${vortexModUid}`);

const stubDir = join(here, "generated");
mkdirSync(stubDir, { recursive: true });
const stubPath = join(stubDir, "uids-stub.ts");
writeFileSync(
  stubPath,
  `// GENERATED by build.mjs - do not edit.\n` +
    `// Value read from ${realUIDsPath.replace(/\\/g, "/")}\n` +
    `export const VORTEX_MOD_UID = "${vortexModUid}";\n`,
  "utf8",
);

const realCheck = readFileSync(realCheckPath, "utf8");
const checkIdMatch = realCheck.match(
  /export const FILE_REQUIREMENTS_CHECK_ID\s*=\s*"([^"]+)"/,
);
if (!checkIdMatch) {
  console.error(
    `Could not read FILE_REQUIREMENTS_CHECK_ID out of ${realCheckPath}.`,
  );
  process.exit(2);
}
console.log(`FILE_REQUIREMENTS_CHECK_ID pinned from Vortex source: ${checkIdMatch[1]}`);

const checkStubPath = join(stubDir, "check-stub.ts");
writeFileSync(
  checkStubPath,
  `// GENERATED by build.mjs - do not edit.\n` +
    `export const FILE_REQUIREMENTS_CHECK_ID = "${checkIdMatch[1]}";\n`,
  "utf8",
);

// The listing content module also imports React components and action
// creators. selectEntries() - the only thing the runner calls - never touches
// them, so they are stubbed out rather than dragging in Vortex's UI graph.
const emptyStubPath = join(stubDir, "empty-stub.ts");
writeFileSync(
  emptyStubPath,
  `// GENERATED by build.mjs - do not edit.\n` +
    `// Stands in for modules the parity runner never calls into.\n` +
    `const unused = () => {\n` +
    `  throw new Error("parity runner called a stubbed Vortex module");\n` +
    `};\n` +
    `export const ListingRow = unused;\n` +
    `export const DetailView = unused;\n` +
    `export const setFileRequirementHidden = unused;\n` +
    `export const downloadFileRequirement = unused;\n` +
    `export const installDownloadedFile = unused;\n`,
  "utf8",
);

// --- bundle ----------------------------------------------------------------

await build({
  entryPoints: [join(here, "src/runner.ts")],
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  outfile: join(here, "dist/runner.mjs"),
  logLevel: "info",
  alias: {
    "@nexusmods/file-dependency-resolver": resolverEntry,
    "@vortex-health-check/mapRequirementsReport": mapperEntry,
    "@/extensions/nexus_integration/util/UIDs": stubPath,
    "@vortex-health-check/FileRequirementsContent": contentEntry,
    "@/extensions/health_check/utils/fileRequirements/fileRequirementActions":
      emptyStubPath,
  },
  plugins: [
    {
      // Relative imports inside Vortex's own tree that we substitute.
      name: "parity-stubs",
      setup(build) {
        build.onResolve({ filter: /checks\/fileRequirementsCheck$/ }, () => ({
          path: checkStubPath,
        }));
        build.onResolve(
          { filter: /components\/file_requirement\/(ListingRow|DetailView)$/ },
          () => ({ path: emptyStubPath }),
        );
        build.onResolve({ filter: /actions\/persistent$/ }, () => ({
          path: emptyStubPath,
        }));
      },
    },
  ],
});

console.log("built dist/runner.mjs");
